name: mapssi
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2


  #추가
  flutter_svg: ^1.0.0

  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  http: ^0.13.6
  geocoding: ^2.1.0

  url_launcher: ^6.0.17
  intl: ^0.17.0 #날짜/숫자 형식 지정 라이브러리
  timer_builder: ^2.0.0 #주기적/동적으로 시간 이벤트를 처리하는 라이브러리
  convert: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_config: ^2.0.0
  flutter_dialogs: ^2.1.1
  provider: ^6.0.1
  get: ^4.6.1
  google_sign_in: ^6.1.0
  kakao_flutter_sdk_user: ^1.4.2
  shared_preferences: ^2.1.1 #로그인 여부 전역에서 체크


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
    - assets/icons/
    - assets/image/
    - assets/weather/
    - assets/clothes/bottoms/
    - assets/clothes/overcoat/
    - assets/clothes/shoes/
    - assets/clothes/tops/

  fonts:
    - family: CoordiIcons
      fonts:
        - asset: fonts/CoordiIcons.ttf

    - family: Cafe24Ssurround
      fonts:
        - asset: fonts/Cafe24Ssurround.ttf

    - family: SUITE
      fonts:
        - asset: fonts/SUITE-Light.ttf
          weight: 300
        - asset: fonts/SUITE-Regular.ttf
          weight: 400
        - asset: fonts/SUITE-Medium.ttf
          weight: 500
        - asset: fonts/SUITE-SemiBold.ttf
          weight: 600
        - asset: fonts/SUITE-Bold.ttf
          weight: 700
        - asset: fonts/SUITE-ExtraBold.ttf
          weight: 800
        - asset: fonts/SUITE-Heavy.ttf
          weight: 900

    - family: Dovemayo_gothic
      fonts:
        - asset: fonts/Dovemayo_gothic.ttf



  uses-material-design: true
