/// Flutter icons Bottoms
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bottoms
///      fonts:
///       - asset: fonts/Bottoms.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bottoms {
  Bottoms._();

  static const _kFontFam = 'Bottoms';
  static const String? _kFontPkg = null;

  static const IconData slim_fit_pants = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trousers = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cargo = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData jogger_pants = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loose_pants = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData short_cargo = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flare_pants = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shorts = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
