/// Flutter icons Overcoat
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Overcoat
///      fonts:
///       - asset: fonts/Overcoat.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Overcoat {
  Overcoat._();

  static const _kFontFam = 'Overcoat';
  static const String? _kFontPkg = null;

  static const IconData bomber = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cardigan = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casual_jacket = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collar_cardigan = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leather_jacket = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData overcoat = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData parka = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sport_jacket = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData windcheater = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData track_jacket = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
