/// Flutter icons Shoes
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Shoes
///      fonts:
///       - asset: fonts/Shoes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Shoes {
  Shoes._();

  static const _kFontFam = 'Shoes';
  static const String? _kFontPkg = null;

  static const IconData chelsea_boot = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dress_shoes = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flat_shoes = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData high_heel = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData running_shoes = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slip_on = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData slipper = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sneakers = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData walker = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
