/// Flutter icons TopClothes
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TopClothes
///      fonts:
///       - asset: fonts/TopClothes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TopClothes {
  TopClothes._();

  static const _kFontFam = 'TopClothes';
  static const String? _kFontPkg = null;

  static const IconData casual_shirt = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casual_sweat_shirt = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casual_t_shirt = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hoodie = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pocket_t_shirt = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData polo_shirt = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reglan_sweat_shirt = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reglan_t_shirt = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleeveless_shirt = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sleeveless_top = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tank_top = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData v_neck_t_shirt = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData zip_hoodie = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
